image: ghcr.io/sushrut1101/docker:arch

variables:
  CONFIG: "config.sh"

TWRP-CI:
  stage: build
  timeout: 3 hours
  script:
    - source config.sh
    - curl -sL https://raw.githubusercontent.com/Recoveries-CI/TWRP-CI/main/scripts/checks.sh | bash
    - curl -sL https://raw.githubusercontent.com/Recoveries-CI/TWRP-CI/main/scripts/sync.sh | bash
    - curl -sL https://raw.githubusercontent.com/Recoveries-CI/TWRP-CI/main/scripts/build.sh | bash
    - curl -sL https://raw.githubusercontent.com/Recoveries-CI/TWRP-CI/main/scripts/upload.sh | bash